# Generated by Django 3.2.12 on 2022-10-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_uid', models.CharField(max_length=100, verbose_name='文章UID')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('positive', models.BooleanField(editable=False, null=True, verbose_name='是否积极')),
                ('prob', models.FloatField(editable=False, null=True, verbose_name='积极估计概率')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'comment',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='HotArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_bid', models.CharField(max_length=100, verbose_name='文章BID')),
                ('article_uid', models.CharField(max_length=100, verbose_name='文章UID')),
                ('article_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('screen_name', models.TextField(verbose_name='用户昵称')),
                ('text', models.TextField(verbose_name='微博正文')),
                ('topics', models.TextField(verbose_name='话题')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('location', models.TextField(verbose_name='发布位置')),
                ('comments_count', models.IntegerField(verbose_name='评论数')),
                ('reposts_count', models.IntegerField(verbose_name='转发数')),
                ('publish_tool', models.TextField(verbose_name='发布工具')),
            ],
            options={
                'verbose_name': '热点文章',
                'verbose_name_plural': '热点文章',
                'db_table': 'hot_article',
                'ordering': ('id',),
            },
        ),
    ]
